#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

@unlink($fileName = 'bin/appgen.phar');
@unlink('bin/appgen');

$p = new Phar($fileName);

$p->startBuffering();
$p->buildFromDirectory(__DIR__, '/\.php$/');
$p->setStub("#!/usr/bin/env php \n" . $p->createDefaultStub('kernel.php'));
$p->stopBuffering();

copy($fileName, 'bin/appgen');
