#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

@unlink($fileName = 'bin/appgen.phar');

$p = new Phar($fileName);

$p->startBuffering();
$p->buildFromDirectory(__DIR__, '/\.php|appgen$/');
$p->setStub($p->createDefaultStub('appgen'));
$p->stopBuffering();
